import type { Metadata } from 'next'
import { EB_Garamond, Inter } from 'next/font/google'
import '@/scss/globals.scss'
import LogoHeading from '@/components/global/LogoHeading/LogoHeading'
import OverlayProvider from '@/components/global/OverlayContextProvider/OverlayContextProvider'

//Using next font optimization to locally host fonts for performance optimization.
const garamond = EB_Garamond({
  subsets: ['latin'],
  variable: '--font-eb-garamond',
  display: 'swap',
})
 
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'LifeAdvice',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${garamond.variable} ${inter.variable}`}>
      <body>
        <OverlayProvider>
          <LogoHeading />
          {children}
        </OverlayProvider>
      </body>
    </html>
  )
}
